
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author phdam
 */
public class telapoke extends javax.swing.JFrame {

    /**
     * Creates new form telapoke
     */
    public telapoke() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        blastoise_img = new javax.swing.JLabel();
        charmander_img = new javax.swing.JLabel();
        outroPokemon_button = new javax.swing.JButton();
        luta_botao1 = new javax.swing.JButton();
        meupokemon_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        blastoise_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blastoise.gif"))); // NOI18N

        charmander_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/charmander3.gif"))); // NOI18N

        outroPokemon_button.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 24)); // NOI18N
        outroPokemon_button.setText("Ver Pokemon adversário");
        outroPokemon_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outroPokemon_buttonActionPerformed(evt);
            }
        });

        luta_botao1.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 24)); // NOI18N
        luta_botao1.setText("FIGHT");
        luta_botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luta_botao1ActionPerformed(evt);
            }
        });

        meupokemon_button.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 24)); // NOI18N
        meupokemon_button.setText("Ver Seu Pokemon");
        meupokemon_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meupokemon_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(charmander_img)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blastoise_img)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(meupokemon_button, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(luta_botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(outroPokemon_button)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(charmander_img, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(blastoise_img, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outroPokemon_button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meupokemon_button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(luta_botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outroPokemon_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outroPokemon_buttonActionPerformed
        // TODO add your handling code here:
       
        Pokemon outroPokemon = new Pokemon("Blatoise","Agua",30);
        
        
        Batalhas batalha1 = new Batalhas();
               
   
        System.out.println("Pokémon Inimigo: ");
        outroPokemon.imprimiPokemon();
        
  JOptionPane.showMessageDialog(null,"Pokémon Inimigo: \n" +
"Nome: Blatoise | Tipo: Agua | Level: 30 | Vida: 245.0 | Ataque: 90.0 | Defesa: 77.0","Pokemon Inimigo",1);
        

    }//GEN-LAST:event_outroPokemon_buttonActionPerformed

    private void luta_botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luta_botao1ActionPerformed
        // TODO add your handling code here:
        Pokemon meuPokemon = new Pokemon("Charmander","Fogo",30);
        
        Pokemon outroPokemon = new Pokemon("Blatoise","Agua",30);
        
        
        Batalhas batalha1 = new Batalhas();
               
        System.out.println("Seu Pokémon: ");
        meuPokemon.imprimiPokemon();
        System.out.println("Pokémon Inimigo: ");
        outroPokemon.imprimiPokemon();
        
        batalha1.meuPokemon(meuPokemon.getNome(), (int) meuPokemon.getVida());
        batalha1.outroPokemon(outroPokemon.getNome(), (int) outroPokemon.getVida());
        
        String vitoria = batalha1.startBattle(meuPokemon, outroPokemon);        
        
        JOptionPane.showMessageDialog(null," A batalha vai começar!...\n" + vitoria);
        
        System.exit(0);

    }//GEN-LAST:event_luta_botao1ActionPerformed

    private void meupokemon_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meupokemon_buttonActionPerformed
        // TODO add your handling code here:
        
        Pokemon meuPokemon = new Pokemon("Charmander","Fogo",30);
        
        Batalhas batalha1 = new Batalhas();
               
        System.out.println("Seu Pokémon: ");
        meuPokemon.imprimiPokemon();
        
        JOptionPane.showMessageDialog(null,"Seu Pokémon: \n" +
"Nome: Charmander | Tipo: Fogo | Level: 30 | Vida: 195.0 | Ataque: 110.0 | Defesa: 57.0","Seu Pokemon",1);
        


    }//GEN-LAST:event_meupokemon_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telapoke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telapoke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telapoke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telapoke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telapoke().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blastoise_img;
    private javax.swing.JLabel charmander_img;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton luta_botao1;
    private javax.swing.JButton meupokemon_button;
    private javax.swing.JButton outroPokemon_button;
    // End of variables declaration//GEN-END:variables
}
